CREATE TABLE data (
	action_type VARCHAR(34) NOT NULL, 
	combined_shot_type VARCHAR(9) NOT NULL, 
	game_event_id INTEGER NOT NULL, 
	game_id INTEGER NOT NULL, 
	lat FLOAT NOT NULL, 
	loc_x INTEGER NOT NULL, 
	loc_y INTEGER NOT NULL, 
	lon FLOAT NOT NULL, 
	minutes_remaining INTEGER NOT NULL, 
	period INTEGER NOT NULL, 
	playoffs INTEGER NOT NULL, 
	season VARCHAR(7) NOT NULL, 
	seconds_remaining INTEGER NOT NULL, 
	shot_distance INTEGER NOT NULL, 
	shot_made_flag INTEGER, 
	shot_type VARCHAR(14) NOT NULL, 
	shot_zone_area VARCHAR(21) NOT NULL, 
	shot_zone_basic VARCHAR(21) NOT NULL, 
	shot_zone_range VARCHAR(15) NOT NULL, 
	team_id INTEGER NOT NULL, 
	team_name VARCHAR(18) NOT NULL, 
	game_date DATE NOT NULL, 
	matchup VARCHAR(11) NOT NULL, 
	opponent VARCHAR(3) NOT NULL, 
	shot_id INTEGER NOT NULL
);
